using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;

namespace CQT.Tests;

/// <summary>
/// Loads test data generated by Python reference implementation.
/// </summary>
public static class TestDataLoader
{
    private static readonly string TestDataPath = Path.Combine(
        AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "testdata");
    private static readonly string FallbackTestDataPath = Path.Combine(
        AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "..", "testdata");

    public static JsonElement LoadTestCase(string name)
    {
        var path = Path.Combine(TestDataPath, $"{name}.json");
        if (!File.Exists(path))
        {
            path = Path.Combine(FallbackTestDataPath, $"{name}.json");
        }
        if (!File.Exists(path))
        {
            throw new FileNotFoundException(
                $"Test data not found in '{TestDataPath}' or '{FallbackTestDataPath}'. " +
                "Run the Python generator to create it.");
        }
            
        var json = File.ReadAllText(path);
        return JsonDocument.Parse(json).RootElement;
    }

    public static double[] GetDoubleArray(JsonElement element)
    {
        var list = new List<double>();
        foreach (var item in element.EnumerateArray())
        {
            list.Add(item.GetDouble());
        }
        return list.ToArray();
    }

    public static double[,] GetDouble2DArray(JsonElement element)
    {
        var rows = new List<double[]>();
        foreach (var row in element.EnumerateArray())
        {
            rows.Add(GetDoubleArray(row));
        }
            
        if (rows.Count == 0) return new double[0, 0];
            
        int nRows = rows.Count;
        int nCols = rows[0].Length;
        var result = new double[nRows, nCols];
            
        for (int i = 0; i < nRows; i++)
        {
            for (int j = 0; j < nCols; j++)
            {
                result[i, j] = rows[i][j];
            }
        }
            
        return result;
    }

    public static Complex[] GetComplexArray(JsonElement element)
    {
        var real = GetDoubleArray(element.GetProperty("real"));
        var imag = GetDoubleArray(element.GetProperty("imag"));
            
        var result = new Complex[real.Length];
        for (int i = 0; i < real.Length; i++)
        {
            result[i] = new Complex(real[i], imag[i]);
        }
        return result;
    }

    public static bool TestDataExists(string name)
    {
        var path = Path.Combine(TestDataPath, $"{name}.json");
        if (File.Exists(path))
            return true;
        path = Path.Combine(FallbackTestDataPath, $"{name}.json");
        return File.Exists(path);
    }
}